name: build docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build documentation
        shell: pwsh
        run: ./Tools/GenerateDocs.ps1
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Commit and push changes
        run: |
          git add docs/
          git commit -m "Update generated documentation"
          git push