name: publish module
on:
  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERYAPIKEY }}
        shell: pwsh
        run: |
          Publish-Module -path ./IntuneGraph -NuGetApiKey $env:NUGET_KEY